networks:
  database:
    external: false

services:
  postgres_athletiquest:
    image: postgis/postgis:17-3.5-alpine
    container_name: postgresql_athletiquest
    environment:
      POSTGRES_USER: athletiquest
      POSTGRES_PASSWORD: athletiquest
      POSTGRES_DB: athletiquest
    ports:
      - '5432:5432'
    volumes:
      - ./db_data_postgresql:/var/lib/postgresql/data
    networks:
      - database

  mongodb_athletiquest:
    image: mongo:8.0.10
    container_name: mongodb_athletiquest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=athletiquest
      - MONGO_INITDB_ROOT_PASSWORD=athletiquest
      - MONGO_INITDB_DATABASE=athletiquest
    ports:
      - '27017:27017'
    volumes:
      - ./db_data_mongodb:/data/db
    networks:
      - database

  athletiquest_api:
    image: ghcr.io/jules-elio/athletiquest_api:latest
    pull_policy: always
    container_name: api_athletiquest
    depends_on:
      - postgres_athletiquest
      - mongodb_athletiquest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_athletiquest:5432/athletiquest
      SPRING_DATASOURCE_USERNAME: athletiquest
      SPRING_DATASOURCE_PASSWORD: athletiquest
      SPRING_DATA_MONGODB_URI: mongodb://athletiquest:athletiquest@mongodb_athletiquest:27017/athletiquest?authSource=admin
    networks:
      - database

