apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiU2NsdXMiLCJwYXNzd29yZCI6ImdocF9zVFZPRG1reWltNjBPNm44MkFHRHVEMU9mTmZkZG0xem5lME0iLCJlbWFpbCI6Imp1bGVzbWFoZS5tYWhlQGdtYWlsLmNvbSIsImF1dGgiOiJVMk5zZFhNNloyaHdYM05VVms5RWJXdDVhVzAyTUU4MmJqZ3lRVWRFZFVReFQyWk9abVJrYlRGNmJtVXdUUT09In19fQ==
